### ISSUE TITLE
Update to symfony/http-foundation 2.5.*

### ISSUE THREAD

**Issue by joksnet** [rawebone/Micro#2]
Just that. Since 2.5 doesn't have any BC and [not many changes](https://github.com/symfony/HttpFoundation/blob/master/CHANGELOG.md). Also, 2.6 is around the corner.

**Comment by rawebone** [comment]
@joksnet I've updated and released 1.0.1, all tests passing so should be good for you.

**Comment by joksnet** [comment]
It's difficult to keep up with dependencies.
